import type { Metadata } from "next";
import { Cormorant, Manrope } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Portfilio",
  description: "Generated by create next app",
};

const manrope = Manrope({
  subsets: ["latin"],
});

const cormorant = Cormorant({
  subsets: ["latin"],
  variable: "--font-cormorant",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="h-full antialiased scroll-smooth">
      <body
        className={`${manrope.className} ${cormorant.variable} min-h-full flex flex-col bg-white transition-all ease-in`}
      >
        {children}
      </body>
    </html>
  );
}
